# Generated by Django 5.0.7 on 2024-07-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=255),
        ),
    ]
